# Generated by Django 5.2.4 on 2025-07-14 21:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Category description (max 1000 characters)', validators=[django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name (2-100 characters, must be unique)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Event category', null=True, on_delete=django.db.models.deletion.CASCADE, to='eventlist.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Event description (max 5000 characters)', validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(help_text='Event end date and time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(help_text='Event start date and time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Event title (1-200 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default=1, help_text='Event venue (required)', on_delete=django.db.models.deletion.CASCADE, to='eventlist.venue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='content',
            field=models.TextField(help_text='Post content'),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Post creation timestamp'),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='event',
            field=models.ForeignKey(help_text='Associated event', on_delete=django.db.models.deletion.CASCADE, to='eventlist.event'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(blank=True, help_text='Venue address', max_length=300),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Venue capacity (positive integer)', null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(help_text='Venue name (2-200 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
